import { MenuPluginMetadata } from '../interfaces/menu-plugin.interface';
import { MenuItemConfig } from '../../settings/micro-modules/ui-permissions/default-menus';

/**
 * Регистрация системных плагинов меню
 * Каждый пункт меню - это плагин
 */
export const SYSTEM_MENU_PLUGINS: MenuPluginMetadata[] = [
  {
    id: 'dashboard',
    name: 'Профиль',
    description: 'Главная страница профиля пользователя',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'dashboard',
      systemId: 'profile',
      type: 'default',
      enabled: true,
      order: 1,
      icon: 'home',
      path: '/dashboard',
      label: 'Профиль',
      labelRu: 'Профиль',
      labelEn: 'Profile',
    },
    order: 1,
  },
  {
    id: 'data',
    name: 'Данные',
    description: 'Управление персональными данными',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'data',
      systemId: 'data',
      type: 'default',
      enabled: true,
      order: 2,
      icon: 'database',
      path: '/data',
      label: 'Данные',
      labelRu: 'Данные',
      labelEn: 'Data',
    },
    order: 2,
  },
  {
    id: 'data-documents',
    name: 'Документы',
    description: 'Управление документами',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'data-documents',
      systemId: 'data-documents',
      type: 'default',
      enabled: true,
      order: 3,
      icon: 'document',
      path: '/data/documents',
      label: 'Документы',
      labelRu: 'Документы',
      labelEn: 'Documents',
    },
    order: 3,
    parentId: 'data', // Вложенность: документы внутри раздела "Данные"
  },
  {
    id: 'data-addresses',
    name: 'Адреса',
    description: 'Управление адресами',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'data-addresses',
      systemId: 'data-addresses',
      type: 'default',
      enabled: true,
      order: 4,
      icon: 'map-pin',
      path: '/data/addresses',
      label: 'Адреса',
      labelRu: 'Адреса',
      labelEn: 'Addresses',
    },
    order: 4,
    parentId: 'data', // Вложенность: адреса внутри раздела "Данные"
  },
  {
    id: 'security',
    name: 'Безопасность',
    description: 'Настройки безопасности',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'security',
      systemId: 'security',
      type: 'default',
      enabled: true,
      order: 5,
      icon: 'shield',
      path: '/security',
      label: 'Безопасность',
      labelRu: 'Безопасность',
      labelEn: 'Security',
    },
    order: 5,
  },
  {
    id: 'family',
    name: 'Семья',
    description: 'Управление семейными данными',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'family',
      systemId: 'family',
      type: 'default',
      enabled: true,
      order: 6,
      icon: 'users',
      path: '/family',
      label: 'Семья',
      labelRu: 'Семья',
      labelEn: 'Family',
    },
    order: 6,
  },
  {
    id: 'work',
    name: 'Работа',
    description: 'Управление рабочими данными',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'work',
      systemId: 'work',
      type: 'default',
      enabled: true,
      order: 7,
      icon: 'briefcase',
      path: '/work',
      label: 'Работа',
      labelRu: 'Работа',
      labelEn: 'Work',
    },
    order: 7,
  },
  {
    id: 'payments',
    name: 'Платежи',
    description: 'Управление платежами',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'payments',
      systemId: 'payments',
      type: 'default',
      enabled: true,
      order: 8,
      icon: 'credit-card',
      path: '/pay',
      label: 'Платежи',
      labelRu: 'Платежи',
      labelEn: 'Payments',
    },
    order: 8,
  },
  {
    id: 'support',
    name: 'Поддержка',
    description: 'Центр поддержки',
    type: 'system',
    version: '1.0.0',
    menuItem: {
      id: 'support',
      systemId: 'support',
      type: 'default',
      enabled: true,
      order: 9,
      icon: 'help-circle',
      path: '/support',
      label: 'Поддержка',
      labelRu: 'Поддержка',
      labelEn: 'Support',
    },
    order: 9,
  },
];

